name: publish

on:
  push:
    tags:
      # - v[0-9].[0-9]+.[0-9]+
      - v**
  # workflow_run:
  #   workflows: ["version, tag and github release"]
  #   types: [completed]
  release:
    # types:
    #   - released
    #   - created
    #   - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - name: Echo
        run: |
          echo "github.event_name: ${{github.event_name}}"
          echo "github.event.action: ${{github.event.action}}"
          echo "$GITHUB_CONTEXT"

