name: publish

on:
  release:
    types:
      - released
      - created
      - published

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - name: Echo
        run: |
          echo "github.event_name: $github.event_name"
          echo "github.event.action: $github.event.action"
          echo "CONTEXT: $GITHUB_CONTEXT"

